Детальная настройка подключения к БД
arrilot/bitrix-models pull request #34
Opened 2020-02-09 19:50 UTC by maltf0

Добавлена поддержка детальной конфигурации подключения к БД, поддержка нескольких БД.
Конфигурация берется из массива `bitrix-models.illuminate-database` конфигурационного файла `.settings.php`.

Пример конфигурации (`.settings.php`):
```php
[
    ...
    'bitrix-models.illuminate-database' => [
        'value' => [
                'default' => getenv('DB_DEFAULT_CONNECTION_NAME'),
                'connections' => [
                    'mysql' => [
                        'driver' => 'mysql',
                        'url' => getenv('DB_MYSQL_URL'),
                        'host' => getenv('DB_MYSQL_HOST'),
                        'port' => getenv('DB_MYSQL_PORT'),
                        'database' => getenv('DB_MYSQL_DATABASE'),
                        'username' => getenv('DB_MYSQL_USERNAME'),
                        'password' => getenv('DB_MYSQL_PASSWORD'),
                        'unix_socket' => getenv('DB_MYSQL_SOCKET'),
                        'charset' => 'utf8',
                        'collation' => 'utf8_unicode_ci',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'strict' => false,
                        'engine' => null,
                        'options' => [],
                    ],
                ],
            ],
        'readonly' => true,
    ],
]
```
Больше примеров подключения: https://github.com/laravel/laravel/blob/5.7/config/database.php

2020-02-12 13:29 UTC, arrilot requested changes

2020-02-12 13:29 UTC, arrilot commented on src/ServiceProvider.php
> +			foreach ($dbConfig['connections'] as $name => $conntection) {
conntection -> connection

2020-02-12 13:29 UTC, arrilot commented on src/ServiceProvider.php
> +		if ($dbConfig = Configuration::getInstance()->get('bitrix-models.illuminate-database')) {
Добавь еще плиз небольшой абзац об этой фиче в документацию

2020-02-12 18:31 UTC, maltf0 commented
Добавил описание в readme.txt
Чукча не очень хороший писатель, но я старался:)

2020-02-16 08:32 UTC, arrilot commented
Отлично, спасибо!

2020-02-16 08:32 UTC, merged